# This is a basic workflow to help you get started with Actions

name: New Release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd LukeWebsite
            git stash && git pull
            cd src
            /home/lukep/.pyenv/bin/pyenv activate websiteEnv
            python -m pip install --upgrade pip
            pip-sync
            cd LukeWebsite
            python manage.py collectstatic --noinput --settings=LukeWebsite.settings.prod
            python manage.py migrate --settings=LukeWebsite.settings.prod
            sudo systemctl restart apache2
