# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      mysql:
          image: mariadb:latest
          env:
            MYSQL_ROOT_PASSWORD: ${{secrets.MYSQLPW}}
            MYSQL_DATABASE: tenmansstatistics
          ports:
            - 3306:3306/tcp
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    env:
      DJANGO_SETTINGS_MODULE: LukeWebsite.settings.testing

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify MariaDB connection
      run: |
        docker ps
        sudo mysql -h localhost -P 3306 --protocol=tcp -e 'SHOW DATABASES' -uroot --password=${{secrets.MYSQLPW}}
    - name: Install Dependencies
      working-directory: ./src
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-sync
    - name: Write DB Conf File
      working-directory: ./src/LukeWebsite
      env:
        DB_CONF: ${{ secrets.DB_CONF }}
      run: |
        mkdir ./privateSettings
        echo "$DB_CONF" >> ./privateSettings/db.cnf
    - name: Write API Key File
      working-directory: ./src/LukeWebsite/tenMans
      env:
        API_FILE: ${{ secrets.API_KEY }}
      run: |
        mkdir ./conf
        echo "$API_FILE" >> ./conf/api.ini
    - name: Build Objects
      working-directory: ./src/LukeWebsite
      run: |
        python manage.py collectstatic --noinput --settings=LukeWebsite.settings.testing
        python manage.py migrate --settings=LukeWebsite.settings.testing
    - name: Run Tests
      working-directory: ./src/LukeWebsite
      run: |
        pytest
    - name: Upload Code Coverage
      uses: codecov/codecov-action@v1.5.0
      with:
        file: ./src/LukeWebsite/coverage.xml
        flags: unittests # optional
        fail_ci_if_error: true
        verbose: true
        
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          export PATH="/home/lukep/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          cd LukeWebsite
          git stash && git pull
          cd src
          pyenv activate websiteEnv
          python -m pip install --upgrade pip
          pip-sync
          cd LukeWebsite
          python manage.py collectstatic --noinput --settings=LukeWebsite.settings.prod
          python manage.py migrate --settings=LukeWebsite.settings.prod
          sudo systemctl restart apache2
